"""
Test script for the model handler system.
This script tests if our handlers work correctly WITHOUT deploying to AWS.
"""

# Add this section at the TOP before other imports
import sys
import os

# Add the src directory to Python's path so it can find the models module
# This gets the directory where this test file is located
test_dir = os.path.dirname(os.path.abspath(__file__))
# Go up one level to aws_dev, then into src
src_dir = os.path.join(os.path.dirname(test_dir), 'src')
# Add to Python's module search path
sys.path.insert(0, src_dir)

# Now the regular imports will work
import json
from models.model_config import get_model_config, get_available_models, MODELS
from models.handlers.anthropic_handler import AnthropicHandler
from models.handlers.qwen_handler import QwenHandler

def test_model_config():
    """Test 1: Check if model configuration is set up correctly."""
    print("\n" + "="*60)
    print("TEST 1: Model Configuration")
    print("="*60)
    
    try:
        # Test getting all available models
        available = get_available_models()
        print(f"✅ Found {len(available)} available models:")
        for model in available:
            print(f"   - {model['id']}: {model['name']} ({model['provider']})")
        
        # Test getting specific model configs
        print("\n📋 Testing model lookups:")
        for model_key in ["claude-sonnet-4", "qwen-2.5-vl"]:
            config = get_model_config(model_key)
            print(f"   ✅ {model_key}: {config['name']}")
        
        # Test invalid model
        print("\n🚫 Testing invalid model (should fail):")
        try:
            config = get_model_config("invalid-model")
            print("   ❌ ERROR: Should have raised an exception!")
        except ValueError as e:
            print(f"   ✅ Correctly raised error: {e}")
        
        print("\n✅ TEST 1 PASSED: Model configuration works!\n")
        return True
        
    except Exception as e:
        print(f"\n❌ TEST 1 FAILED: {e}\n")
        return False

def test_anthropic_handler():
    """Test 2: Check if Anthropic handler builds correct payload."""
    print("\n" + "="*60)
    print("TEST 2: Anthropic Handler")
    print("="*60)
    
    try:
        # Create handler
        handler = AnthropicHandler()
        print("✅ Created AnthropicHandler instance")
        
        # Test payload building
        payload = handler.build_payload(
            image_b64="fake_base64_data_for_testing",
            image_mime="image/jpeg",
            prompt="Test prompt: describe this image",
            max_tokens=512,
            temperature=0.7
        )
        
        # Verify payload structure
        print("\n📋 Checking payload structure:")
        assert "anthropic_version" in payload, "Missing anthropic_version"
        print("   ✅ Has anthropic_version")
        
        assert "max_tokens" in payload, "Missing max_tokens"
        print("   ✅ Has max_tokens")
        
        assert "messages" in payload, "Missing messages array"
        print("   ✅ Has messages array")
        
        assert payload["messages"][0]["role"] == "user", "Wrong role"
        print("   ✅ Correct role: user")
        
        content = payload["messages"][0]["content"]
        assert len(content) == 2, "Should have 2 content blocks (image + text)"
        print("   ✅ Has 2 content blocks (image + text)")
        
        assert content[0]["type"] == "image", "First block should be image"
        print("   ✅ First block is image")
        
        assert content[1]["type"] == "text", "Second block should be text"
        print("   ✅ Second block is text")
        
        # Test response parsing
        print("\n📋 Testing response parsing:")
        mock_response = {
            "content": [
                {
                    "type": "text",
                    "text": "This is a test caption generated by Claude"
                }
            ]
        }
        
        result = handler.parse_response(mock_response)
        assert result == "This is a test caption generated by Claude"
        print(f"   ✅ Correctly parsed: '{result}'")
        
        print("\n✅ TEST 2 PASSED: Anthropic handler works!\n")
        return True
        
    except Exception as e:
        print(f"\n❌ TEST 2 FAILED: {e}\n")
        import traceback
        traceback.print_exc()
        return False

def test_qwen_handler():
    """Test 3: Check if QWen handler builds correct payload."""
    print("\n" + "="*60)
    print("TEST 3: QWen Handler")
    print("="*60)
    
    try:
        # Create handler
        handler = QwenHandler()
        print("✅ Created QwenHandler instance")
        
        # Test payload building
        payload = handler.build_payload(
            image_b64="fake_base64_data_for_testing",
            image_mime="image/jpeg",
            prompt="Test prompt: describe this image",
            max_tokens=512,
            temperature=0.7
        )
        
        # Verify payload structure
        print("\n📋 Checking payload structure:")
        assert "prompt" in payload, "Missing prompt"
        print("   ✅ Has prompt")
        
        assert "<|vision_start|>" in payload["prompt"], "Missing vision tokens"
        print("   ✅ Has vision tokens")
        
        assert "images" in payload, "Missing images array"
        print("   ✅ Has images array")
        
        assert "max_new_tokens" in payload, "Missing max_new_tokens"
        print("   ✅ Has max_new_tokens (not max_tokens)")
        
        assert payload["temperature"] == 0.7, "Wrong temperature"
        print("   ✅ Correct temperature: 0.7")
        
        # Test response parsing
        print("\n📋 Testing response parsing:")
        mock_response = {
            "choices": [
                {
                    "text": "This is a test caption generated by QWen"
                }
            ]
        }
        
        result = handler.parse_response(mock_response)
        assert result == "This is a test caption generated by QWen"
        print(f"   ✅ Correctly parsed: '{result}'")
        
        print("\n✅ TEST 3 PASSED: QWen handler works!\n")
        return True
        
    except Exception as e:
        print(f"\n❌ TEST 3 FAILED: {e}\n")
        import traceback
        traceback.print_exc()
        return False

def test_factory_pattern():
    """Test 4: Check if factory function creates correct handlers."""
    print("\n" + "="*60)
    print("TEST 4: Factory Pattern")
    print("="*60)
    
    try:
        # We'll test the factory logic directly without importing lambda_function
        # (lambda_function needs boto3 which isn't installed locally)
        
        print("\n📋 Testing factory logic manually:")
        
        # Test Claude handler creation logic
        print("\n   Testing Claude model:")
        config = get_model_config("claude-sonnet-4")
        provider = config["provider"]
        
        if provider == "anthropic":
            handler = AnthropicHandler()
            print(f"   ✅ Provider: {provider}")
            print(f"   ✅ Created: {type(handler).__name__}")
        else:
            raise ValueError(f"Wrong provider: {provider}")
        
        # Test QWen handler creation logic
        print("\n   Testing QWen model:")
        config = get_model_config("qwen-2.5-vl")
        provider = config["provider"]
        
        if provider == "qwen":
            handler = QwenHandler()
            print(f"   ✅ Provider: {provider}")
            print(f"   ✅ Created: {type(handler).__name__}")
        else:
            raise ValueError(f"Wrong provider: {provider}")
        
        # Test unsupported provider handling
        print("\n   Testing unsupported provider:")
        try:
            # Temporarily add a fake model with unsupported provider
            MODELS["test-fake"] = {"provider": "unsupported", "enabled": True}
            config = get_model_config("test-fake")
            provider = config["provider"]
            
            if provider == "anthropic":
                handler = AnthropicHandler()
            elif provider == "qwen":
                handler = QwenHandler()
            else:
                # This should happen for unsupported providers
                raise ValueError(f"No handler for provider: {provider}")
            
            print("   ❌ Should have raised an error!")
            
        except ValueError as e:
            print(f"   ✅ Correctly raised error for unsupported provider")
        finally:
            # Clean up the fake model
            if "test-fake" in MODELS:
                del MODELS["test-fake"]
        
        print("\n✅ TEST 4 PASSED: Factory pattern logic works!")
        print("   (Note: Skipped full lambda_function test - requires AWS boto3)\n")
        return True
        
    except Exception as e:
        print(f"\n❌ TEST 4 FAILED: {e}\n")
        import traceback
        traceback.print_exc()
        return False
    
def run_all_tests():
    """Run all tests and report results."""
    print("\n" + "="*60)
    print("🧪 RUNNING MODEL HANDLER TESTS")
    print("="*60)
    
    results = {
        "Model Configuration": test_model_config(),
        "Anthropic Handler": test_anthropic_handler(),
        "QWen Handler": test_qwen_handler(),
        "Factory Pattern": test_factory_pattern()
    }
    
    # Summary
    print("\n" + "="*60)
    print("📊 TEST SUMMARY")
    print("="*60)
    
    for test_name, passed in results.items():
        status = "✅ PASSED" if passed else "❌ FAILED"
        print(f"{test_name}: {status}")
    
    total = len(results)
    passed = sum(results.values())
    
    print(f"\nTotal: {passed}/{total} tests passed")
    
    if passed == total:
        print("\n🎉 ALL TESTS PASSED! Your backend is ready!")
    else:
        print(f"\n⚠️  {total - passed} test(s) failed. Please fix the issues above.")
    
    return passed == total

if __name__ == "__main__":
    run_all_tests()